# Generated by Django 4.2.7 on 2025-07-15 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('local', 'Local'), ('provincial', 'Provincial'), ('federal', 'Federal')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('party', models.CharField(max_length=100)),
                ('candidate', models.CharField(max_length=255)),
                ('votes', models.PositiveIntegerField()),
                ('is_winner', models.BooleanField(default=False)),
                ('turnout_percentage', models.FloatField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
        ),
    ]
