# Generated by Django 4.2.7 on 2025-07-15 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResultFederal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=100)),
                ('votes', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResultMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=100)),
                ('votes', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FederalConstituency',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalWard',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('municipality', models.CharField(max_length=100)),
                ('ward_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ElectionResult',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='electionresultmunicipal',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipalward'),
        ),
        migrations.AddField(
            model_name='electionresultfederal',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.federalconstituency'),
        ),
    ]
