# Generated by Django 4.2.7 on 2025-07-15 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_electionresultfederal_electionresultmunicipal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_type', models.CharField(choices=[('federal', 'Federal'), ('provincial', 'Provincial'), ('local', 'Local')], max_length=20)),
                ('candidate_name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('votes', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.federalconstituency')),
            ],
        ),
        migrations.RemoveField(
            model_name='electionresultmunicipal',
            name='ward',
        ),
        migrations.DeleteModel(
            name='ElectionResultFederal',
        ),
        migrations.DeleteModel(
            name='ElectionResultMunicipal',
        ),
        migrations.DeleteModel(
            name='MunicipalWard',
        ),
    ]
